- hosts: local
  name: Install OSX Homebrew Packages
  become: false

  # These are the tasks we want to perform before we install any of our packages...
  pre_tasks:
  - name: Ensuring Homebrew Is Installed
    stat:
      path: "/opt/homebrew/bin/brew"
    register: "homebrew_check"

  - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
    fail:
      msg: "Homebrew is missing...Install from http://brew.sh/"
    when: >
          not homebrew_check.stat.exists and
          not install_homebrew_if_missing

  - name: Installing Homebrew
    shell: |
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/edermazariegos/.zprofile
      eval "$(/opt/homebrew/bin/brew shellenv)"
      brew doctor
      git -C $(brew --repo homebrew/core) checkout master
    when: >
          not homebrew_check.stat.exists and
          install_homebrew_if_missing
  roles:
  - mac-setup